### ISSUE TITLE
Update for Contao 4.9

### ISSUE THREAD

**Issue by onemarshall** [c4y/reviews#1]
Hi could you update the code so it can be installed for Contao 4.9, please.

Rob

**Comment by c4y** [comment]
Do you have any issues? I use the bundle in one 4.9 project without any issues?

**Comment by onemarshall** [comment]
Hi, When I run composer require c4y/reviews, I'm getting this message!

Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for c4y/reviews ^0.0.1 -> satisfiable by c4y/reviews[0.0.1].
- Conclusion: remove contao/manager-bundle 4.9.9
- Conclusion: don't install contao/manager-bundle 4.9.9
- c4y/reviews 0.0.1 requires contao/core-bundle 4.8.* -> satisfiable by contao/core-bundle[4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8].

I am running the Contao Managed Edition 4.9.9
Thanks

**Comment by c4y** [comment]
I have updated the composer.json with the tag 0.0.2
