### ISSUE TITLE
Add English translation

### ISSUE THREAD

**Issue by onemarshall** [c4y/reviews#2]
Hi, Could you please add the English translation? I could provide the translation files.

Thanks

**Comment by c4y** [comment]
Sure. Make a pull request or email the files to me.

**Comment by onemarshall** [comment]
Great thanks!

**Comment by onemarshall** [comment]
Hi, I have attached the english translation, thanks.

[en.zip](https://github.com/c4y/reviews/files/5469018/en.zip)
