### ISSUE TITLE
Not to install in Contao 4.13

### ISSUE THREAD

**Issue by Wedego** [c4y/reviews#4]
First of all thanks for the tool.
After updating to Contao 4.13 you get errors.
A new installation under Contao 4.13 results in the following errors:
`composer update c4y/reviews contao/conflicts
> Resolving dependencies using Composer Cloud v3.3.3
!!! Current server is sponsored by: Contao Association !!!
[6.7MiB/0.17s] Loading composer repositories with package information
[26.0MiB/11.11s] Updating dependencies
[42.2MiB/11.40s] Your requirements could not be resolved to an installable set of packages.
[42.2MiB/11.40s] 
  Problem 1
    - Root composer.json requires c4y/reviews ^0.0.3 -> satisfiable by c4y/reviews[0.0.3].
    - c4y/reviews 0.0.3 requires symfony/framework-bundle ^4 -> found symfony/framework-bundle[v4.0.0, ..., v4.4.38] but these were not loaded, likely because it conflicts with another require.
[42.2MiB/11.40s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[13.4MiB/11.43s] Memory usage: 13.42MB (peak: 133.46MB), time: 11.44s.
[13.4MiB/11.43s] Finished Composer Cloud resolving.

thanks a lot for reading

**Comment by fiedsch** [comment]
Die Requirements des Bundles und von Contao passen nicht zusammen:
* Bundle `"symfony/framework-bundle": "^4"`
* Contao 4.13 `"symfony/framework-bundle": "^5.4"`

**Comment by c4y** [comment]
I will fix it this week

**Comment by Wedego** [comment]
OK super Dankeschön

**Comment by fiedsch** [comment]
@Wedego wenn Du das Issue schließt, bevor @c4y es gefixt hat findet man es nicht mehr (so leicht). Womöglich macht dann jemand anderes ein neues Issue zum gleichen Thema auf.

**Comment by Wedego** [comment]
ohh danke für den Hinweis, schön wenn jemand mitliest

**Comment by c4y** [comment]
Sollte jetzt laufen.

**Comment by wedega** [comment]
Hallo Oliver,
vielen Dank für die Anpassung, das Tool funktioniert wieder.
Schöner Hingucker ;)
Beste Grüße

**Comment by Wedego** [comment]
Hallo und guten Tag,
ich würde sehr gerne haste installieren wegen Notifikationscenter Update.
Leider würde dann das schöne Toole c4y nicht mehr funktionieren, welches ich auf der Seite gerne als Gimick hätte.
Folgende Fehler gibt es:`  Problem 1
    - Root composer.json requires codefog/contao-haste ^5.1, found codefog/contao-haste[5.1.0, ..., 5.1.11] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - c4y/reviews is locked to version 0.0.7 and an update of this package was not requested.
    - c4y/reviews 0.0.7 requires codefog/contao-haste ^4.23 -> found codefog/contao-haste[4.23.0, ..., 4.25.26] but it conflicts with your root composer.json require (^5.1).
  Problem 3`
ein Fix wäre echt sehr toll.
Dankeschön

**Comment by c4y** [comment]
Bitte einmal die neue Version testen.

**Comment by wedega** [comment]
Dankeschön, super, der test dauert leider noch ein wenig. Wir sind im Moment noch in der urlaubswoche und die Handwerker sind noch da.
Beste Grüße
Gottfried Weber

----------------------------------------

05.09.2023 21:16:27 Oliver Lohoff ***@***.***>:

**Comment by Wedego** [comment]
Hallo Oliver,
Dankeschön!
Mit dem neuen Update Haste erfolgreich auf Version 5,1,1 
Ebenfalls Notification Center auf 1.7.2
perfekt nun mit dem klasse Review Tool c4y
Dankeschön und gute Zeit

**Comment by wedega** [comment]
Hallo nochmal mit fast gleichem Problem.
Neues Haste Update verhindert die Aktualisierung mit c4y
Das ist das Protokoll:
`Problem 1
    - Root composer.json requires codefog/contao-haste ^5.2 -> satisfiable by codefog/contao-haste[5.2.0, 5.2.1, 5.2.2].
    - Conclusion: don't install symfony/mime v6.4.8 (conflict analysis result)
    - Conclusion: don't install symfony/mime v5.4.26 (conflict analysis result)
    - Conclusion: don't install symfony/mime[v5.4.40] | install symfony/mime[v7.1.0] (conflict analysis result)
    - Conclusion: don't install symfony/mime v7.1.0 (conflict analysis result)
    - Conclusion: don't install symfony/mime v7.1.1 (conflict analysis result)
    - c4y/reviews 0.0.8 requires contao/core-bundle ^4.13 -> satisfiable by contao/core-bundle[4.13.0, ..., 4.13.44].
    - c4y/reviews is locked to version 0.0.8 and an update of this package was not requested.
    - codefog/contao-haste[5.2.0, ..., 5.2.2] require symfony/mime ^6.0 || ^7.0 -> satisfiable by symfony/mime[v6.0.0, ..., v6.4.8, v7.0.0, ..., v7.1.1].
    - You can only install one version of a package, so only one of these can be installed: symfony/mime[v5.2.5, ..., v5.4.40, v6.0.0, ..., v6.4.8, v7.0.0, ..., v7.1.1].
    - contao/core-bundle 4.13.44 requires symfony/mime ^5.4 -> satisfiable by symfony/mime[v5.4.0, ..., v5.4.40].
    - Conclusion: don't install symfony/mime v5.4.23 (conflict analysis result)`
Vielleicht ist das fixen ja machbar, es wäre sehr schade wenn das c4y nicht mehr zu verwenden wäre.
Liebe Grüße
