### ISSUE TITLE
Nach Erfolgter Bewertung The server returned a "404 Not Found".

### ISSUE THREAD

**Issue by Wedego** [c4y/reviews#5]
Hallo und guten Tag,
ich würde gerne diese Erweiterung nutzen. Leider gibt es ein Problem welches ich nicht lösen kann. 
Installiert nach Anleitung, das Badge wird auch angezeigt. Bewertungen kann man erstellen.
Eine Einladung verschicken funktioniert und der Eingeladene kann auch bewerten.
Nach der Bewertung kommt aber dann: The server returned a "404 Not Found".
die Weiterleitung zu der Erfolgsseite funktioniert nicht.
Im Link: https://domainname.de/kundenmeinung/kundenmeinung/bewertung-erfolgt.html
gibt es doppelte Werte.
Der direkte Aufruf der Formularseite endet ebenfalls in einem 404 Fehler.
https://domainname.de/preview.php/kundenmeinung/preview.php/kundenmeinung/bewertung-ungueltiger-token.html
mit doppelten Einträgen im URL
Ich würde mich über eine Hilfe sehr freuen.
Dankesehr

**Comment by c4y** [comment]
Das würde ich mir gerne mal gerne per Remotesitzung anschauen. Bitte mir einmal eine E-Mail mit den Kontaktdaten schicken (info@contao4you.de)

**Comment by Wedego** [comment]
E-Mail ist unterwegs ;)
Dankeschön

**Comment by c4y** [comment]
Der Fehler lag an der fehlerhaften (relativen) Erstellung der URLs im Bundle. Das Problem wurde in 0.0.5 behoben.

**Comment by Wedego** [comment]
Toller Service, wenn das immer so wäre, es wäre alles gut.
